### ISSUE TITLE
Auto validation with custom model binder

### ISSUE THREAD

**Issue by cris770** [SharpGrip/FluentValidation.AutoValidation#11]
Hi,

I am trying to use auto request validation in an app that uses a custom model binder. 
Looking at the code [here   ](https://github.com/SharpGrip/FluentValidation.AutoValidation/blob/bce479a114aa982419c7089e6fd39b99ab16ece3/FluentValidation.AutoValidation.Mvc/src/Filters/FluentValidationAutoValidationActionFilter.cs#L57), I see the accepted binding sources are Query, Form and Body. Would it be possible to extend that to allow custom binding sources as well? 

Thank you!

**Comment by mvdgun** [comment]
Hi there! I haven't used custom binding source yet. Could you post some code to help me understand how the binding works? I do see a `BindingSource.Custom` option in the .NET framework so I guess we can make it work.

**Comment by JonAdamsFromNC** [comment]
I actually have a PR I'm hoping to submit today with this exact feature, as I had a need for it. @mvdgun, is it worth me submitting that or have you started implementation?

**Comment by cris770** [comment]
@JonAdamsFromNC  you can go ahead an submit the PR. 
I was trying to use a variation of [FromHybrid ](https://github.com/billbogaiv/hybrid-model-binding) model binding, but apart from the auto validation issues I had a few other problems that made me decide to go back to the default model binding. 
But I do think adding support for custom binders will be a nice feature for this great library.
