### ISSUE TITLE
add FluentValidationAutoValidationActionFilter BindingSource.Path

### ISSUE THREAD

**Issue by madostie** [SharpGrip/FluentValidation.AutoValidation#15]
Hi.  I would like to use your extension for my application but for one of my end endpoint (PUT with id from route) and data from the body payload the validator is not being invoked.

[HttpPut]
[Route("/mymodule/{identifier}")]
public override async Task<ActionResult<PerturbationDto>> HandleAsync([FromRoute] UpdateMyModuleCommand request, CancellationToken cancellationToken = default)

 public class UpdateMyModuleCommand
    {
        [FromRoute(Name = "identifier")] public string Identifier { get; set; }
        [FromBody] public UpdateMyModuleCommandParams Params { get; set; }

        public class UpdateMyModuleCommandParams
        {
            public string Name { get; set; }
            .... etc
         }

if in the OnActionExecutionAsync of the FluentValidationAutoValidationActionFilter,
I add this condition then my validator is invoked properly.

Could you please add a confguration EnableRouteBindingSourceAutomaticValidation with the BindingSource.Path in the next version.
Thanks.

  if (subject != null && parameterType.IsCustomType() &&
                            ((autoValidationMvcConfiguration.EnableBodyBindingSourceAutomaticValidation && bindingSource == BindingSource.Body) ||
                             (autoValidationMvcConfiguration.EnableFormBindingSourceAutomaticValidation && bindingSource == BindingSource.Form) ||
                             (autoValidationMvcConfiguration.EnableQueryBindingSourceAutomaticValidation && bindingSource == BindingSource.Query) ||
                             (autoValidationMvcConfiguration.EnableCustomBindingSourceAutomaticValidation && bindingSource == BindingSource.Custom) ||
                             (bindingSource == BindingSource.Path)
                            )
                           )
                        {

**Comment by mvdgun** [comment]
@madostie I just created a PR for it, I would appreciate it if could you take a quick look at it.

**Comment by madostie** [comment]
Just did, looks good.  Thanks for this speedy addition.  When do you plan to release 1.3?

**Comment by mvdgun** [comment]
There is still 1 remaining issue on the 1.3 roadmap: #13. If that one gets resolved 1.3 will release.

**Comment by mvdgun** [comment]
@madostie v1.3.0 just got released
