### ISSUE TITLE
Enable the user to customize the validation context based on MVC context

### ISSUE THREAD

**Issue by hichemaichour** [SharpGrip/FluentValidation.AutoValidation#21]
In [FluentValidation.AspNetCore](https://github.com/FluentValidation/FluentValidation.AspNetCore/), there is a support for `BeforeAspNetValidation` and `AfterAspNetValidation` in [here](https://github.com/FluentValidation/FluentValidation.AspNetCore/blob/347b0535e5fe93bdc39ca031b3f971e0af1619b4/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs#L143C5-L143C95). It will be useful to have something similar here as well.

**Comment by mvdgun** [comment]
Hi @hichemaichour, thanks for your suggestion, looks interesting!

**Comment by hichemaichour** [comment]
just saw the branch, it would be beneficial to have the validator itself able to implement `IValidationInterceptor`, this way, each validator can populate the validation context with what's needed from the mvc context, similar to [here](https://github.com/FluentValidation/FluentValidation.AspNetCore/blob/347b0535e5fe93bdc39ca031b3f971e0af1619b4/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs#L131C25-L131C59)

**Comment by mvdgun** [comment]
@hichemaichour I just pushed new code to that branch splitting basically creating a per validator interceptor and a global one that always fires (if present in the service container). Does that help you?

**Comment by mvdgun** [comment]
@hichemaichour this one just got released in v1.4!
