### ISSUE TITLE
Accessing ValidationFailure from ValidationContext

### ISSUE THREAD

**Issue by farshidnz** [SharpGrip/FluentValidation.AutoValidation#36]
Currently `ValidationFailure` are internal in `ValidationContext` in` IValidationContext.cs`. Is there a way to access the Failures. I would like to check the severity of the validations.
Any suggestions will be appreciated .

**Comment by mvdgun** [comment]
Hi @farshidnz, this library doesn't expose the ValidationContext and IValidationContext types, those are part of the FluentValidation library. Perhaps post your question in the FluentValidation repo?
