### ISSUE TITLE
Add to Readme thelimitation that Controllers that inherit from APIController wont have validation trigger automatically

### ISSUE THREAD

**Issue by francis04j** [SharpGrip/FluentValidation.AutoValidation#39]
Validators are not triggered automatically for NET Projects that make use of ApiController attribute and conventions as described [here](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/actions?view=aspnetcore-8.0#what-is-a-controller).

This mean that if your controller does not inherit ControllerBase or other controller based classes that are provided out of the box, validators won't get triggered automatically

Issue here: https://github.com/SharpGrip/FluentValidation.AutoValidation/issues/35#issue-2254683309

Code culprit here: https://github.com/SharpGrip/FluentValidation.AutoValidation/blob/master/FluentValidation.AutoValidation.Mvc/src/Filters/FluentValidationAutoValidationActionFilter.cs

**Comment by mvdgun** [comment]
Hi @francis04j, could you check out https://github.com/SharpGrip/FluentValidation.AutoValidation/pull/40? I think that solves your problem.
