### ISSUE TITLE
How do I use this for Async validation?

### ISSUE THREAD

**Issue by acnicholls-kroll** [SharpGrip/FluentValidation.AutoValidation#48]
Hi,

I've just found your tool and after spending a few minutes looking at the documentation and trying to use the package in my solution, I see that it's not working quite yet.  

I have added "AutoValidation" with "All" strategy, but am not seeing the validators hit, and when I do, I'm seeing this error ` The service provider has not been configured to work with FluentValidation. Making use of InjectValidator or GetServiceProvider is only supported when using the automatic MVC integration.`

I thought that using this package would allow for using `MustAsync` on my RuleFor statements.  How do I use this package to enable using IServiceProvider in my validators?  I am using the `ValidationContext.GetRequiredService` method in my validators to find my services, but as you see above, this does not seem to be possible.

**Comment by acnicholls-kroll** [comment]
I have written `IRuleBuilder` extensions, which did accept repository classes and performed db checks in an async manner.  But the repo layer classes instantiate EFCore DbContext's and when run async this has concurrent access issues with the DbContext.  So, I thought I could use FV's ValidationContext to get a ServiceProvider and make the repo classes transient so the validation can perform multiple db queries concurrently and this would even make validation faster, but EFCore is preventing that with the concurrent operation limit.

**Comment by mvdgun** [comment]
I don't do any injects in extension methods. Normally I create something like a `RemoteDataValidator` class which I inject into the validators directly, methods on that class I call from either `Must` or `MustAsync`.

**Comment by acnicholls-kroll** [comment]
does your `RemoteDataValidator` class take constructor injection or method injection?  sounds like constructor injection might be overkill if you don't use all the repository classes.

**Comment by mvdgun** [comment]
Closing since this isn't a bug within the library.
