### ISSUE TITLE
Is it possible to control the schema response in ASP.NET Core?

### ISSUE THREAD

**Issue by xplatsolutions** [SharpGrip/FluentValidation.AutoValidation#5]
I would like to set my own response schema in the 400 Bad Request response.

e.g.

```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-0a4404bdf847cb8cf5f696aac649ee61-5dff3d630c7d9c63-00",
    "errors": {
        "ShownGenderOnProfile": [
            "ShownGenderOnProfile must not be empty"
        ]
    }
}
```

I am using the auto-validation package` SharpGrip.FluentValidation.AutoValidation.Mvc`.

**Comment by mvdgun** [comment]
Hi @xplatsolutions, interesting feature. Perhaps it's already possible by customizing the default problem details as explained here: https://learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0#implement-problemdetailsfactory. 

Let me look into it and if it's not possible I'll integrate it into the MVC package and perhaps the Minimal APIs package.

**Comment by xplatsolutions** [comment]
That would be amazing if we figure it out, can be tricky but I imagine something like adding our own JSON for each error.

**Comment by mvdgun** [comment]
I just finished the initial work for a custom result factory. In your case it would work something like this:

```
using SharpGrip.FluentValidation.AutoValidation.Mvc.Extensions;

builder.Services.AddFluentValidationAutoValidation(configuration =>
{
    // Replace the default result factory with a custom implementation.
    configuration.OverrideDefaultResultFactoryWith<CustomResultFactory>();
});

public class CustomResultFactory : IFluentValidationAutoValidationResultFactory
{
    public IActionResult CreateActionResult(ActionExecutingContext context, ValidationProblemDetails? validationProblemDetails)
    {
        return new BadRequestObjectResult(new {Title = "Validation errors", ValidationErrors = validationProblemDetails?.Errors});
    }
}
```

You can return a fully custom response when the model state is invalid. You will be able to access the `ValidationProblemDetails` containing the validation errors and the full `ActionExecutingContext`. Would something like this help you?

**Comment by xplatsolutions** [comment]
This looks like exactly what I need to create my own custom response with all the errors! I can try it out ASAP if you want :)

**Comment by mvdgun** [comment]
Hi @xplatsolutions, I just released the v1.1.0 versions of the packages containing the option for providing a custom result factory.

**Comment by xplatsolutions** [comment]
I will check it out ASAP! Thanks for this one

**Comment by xplatsolutions** [comment]
Confirming the approach worked like a charm! Thank you

**Comment by mvdgun** [comment]
Awesome! Thanks for getting back.
